import { posts } from "@/types";


export const POSTS:posts[]=[
    {
        id: 1,
        category: 'TypeScript',
        title: 'Introduction à TypeScript',
        caption: 'Découvrez comment TypeScript peut améliorer votre développement JavaScript.',
        date: '2023-10-01',
        minuteToRead: 5,
        author: 'Jean Dupont',
        nbLikes: 120,
        nbComments: 10,
        slug: 'introduction-a-typescript',
        url: 'https://example.com/introduction-a-typescript'
    },
    {
        id: 2,
        category: 'React',
        title: 'Les bases de React',
        caption: 'Apprenez à créer des interfaces utilisateur avec React.',
        date: '2023-09-28',
        minuteToRead: 7,
        author: 'Marie Curie',
        nbLikes: 80,
        nbComments: 5,
        slug: 'bases-de-react',
        url: 'https://example.com/bases-de-react'
    },
    {
        id: 3,
        category: 'JavaScript',
        title: 'Comprendre les Promesses en JavaScript',
        caption: 'Tout ce que vous devez savoir sur les Promesses et leur utilisation.',
        date: '2023-09-25',
        minuteToRead: 6,
        author: 'Paul Martin',
        nbLikes: 150,
        nbComments: 8,
        slug: 'comprendre-promesses-javascript',
        url: 'https://example.com/comprendre-promesses-javascript'
    },
    {
        id: 4,
        category: 'Node.js',
        title: 'Comment utiliser Node.js',
        caption: 'Guide complet pour commencer avec Node.js.',
        date: '2023-09-15',
        minuteToRead: 8,
        author: 'Alice Dupuis',
        nbLikes: 200,
        nbComments: 12,
        slug: 'utiliser-nodejs',
        url: 'https://example.com/utiliser-nodejs'
    },
    {
        id: 5,
        category: 'CSS',
        title: 'CSS Grid vs Flexbox',
        caption: 'Quand utiliser CSS Grid et quand utiliser Flexbox ?',
        date: '2023-09-10',
        minuteToRead: 5,
        author: 'Robert Leblanc',
        nbLikes: 95,
        nbComments: 6,
        slug: 'css-grid-vs-flexbox',
        url: 'https://example.com/css-grid-vs-flexbox'
    },
    {
        id: 6,
        category: 'Responsive Design',
        title: 'Les meilleures pratiques pour le responsive design',
        caption: 'Comment rendre votre site web accessible sur tous les appareils.',
        date: '2023-08-30',
        minuteToRead: 10,
        author: 'Emma Dubois',
        nbLikes: 130,
        nbComments: 7,
        slug: 'meilleures-pratiques-responsive',
        url: 'https://example.com/meilleures-pratiques-responsive'
    },
    {
        id: 7,
        category: 'Sécurité Web',
        title: 'Sécurité des applications web',
        caption: 'Les fondamentaux de la sécurité pour les développeurs web.',
        date: '2023-08-20',
        minuteToRead: 9,
        author: 'Marc Petit',
        nbLikes: 110,
        nbComments: 9,
        slug: 'securite-applications-web',
        url: 'https://example.com/securite-applications-web'
    },
    {
        id: 8,
        category: 'Vue.js',
        title: 'Introduction à Vue.js',
        caption: 'Démarrez avec Vue.js pour créer des applications web interactives.',
        date: '2023-08-15',
        minuteToRead: 7,
        author: 'Sophie Martin',
        nbLikes: 85,
        nbComments: 4,
        slug: 'introduction-a-vuejs',
        url: 'https://example.com/introduction-a-vuejs'
    },
    {
        id: 9,
        category: 'Débogage',
        title: 'Débogage avec Chrome DevTools',
        caption: 'Apprenez à utiliser DevTools pour déboguer vos applications.',
        date: '2023-08-10',
        minuteToRead: 6,
        author: 'Lucas Bernard',
        nbLikes: 70,
        nbComments: 11,
        slug: 'debugging-chrome-devtools',
        url: 'https://example.com/debugging-chrome-devtools'
    },
    {
        id: 10,
        category: 'API',
        title: 'API RESTful : Guide Complet',
        caption: 'Tout ce que vous devez savoir sur la création et l’utilisation des API RESTful.',
        date: '2023-08-05',
        minuteToRead: 12,
        author: 'Chloé Lefevre',
        nbLikes: 160,
        nbComments: 15,
        slug: 'api-restful-guide',
        url: 'https://example.com/api-restful-guide'
    },
    {
        id: 11,
        category: 'Redux',
        title: 'Gestion de l’état avec Redux',
        caption: 'Apprenez à gérer l’état de votre application avec Redux.',
        date: '2023-07-30',
        minuteToRead: 8,
        author: 'Nicolas Roche',
        nbLikes: 90,
        nbComments: 3,
        slug: 'gestion-etat-avec-redux',
        url: 'https://example.com/gestion-etat-avec-redux'
    },
    {
        id: 12,
        category: 'GraphQL',
        title: 'Introduction à GraphQL',
        caption: 'Découvrez comment GraphQL peut simplifier vos requêtes d’API.',
        date: '2023-07-25',
        minuteToRead: 7,
        author: 'Laura Simon',
        nbLikes: 140,
        nbComments: 6,
        slug: 'introduction-a-graphql',
        url: 'https://example.com/introduction-a-graphql'
    },
    {
        id: 13,
        category: 'Optimisation Web',
        title: 'Optimisation des performances web',
        caption: 'Techniques pour améliorer la vitesse de votre site web.',
        date: '2023-07-20',
        minuteToRead: 9,
        author: 'Antoine Giraud',
        nbLikes: 155,
        nbComments: 10,
        slug: 'optimisation-performances-web',
        url: 'https://example.com/optimisation-performances-web'
    },
    {
        id: 14,
        category: 'Extensions Chrome',
        title: 'Meilleures extensions Chrome pour les développeurs',
        caption: 'Découvrez les extensions qui facilitent votre quotidien de développeur.',
        date: '2023-07-15',
        minuteToRead: 5,
        author: 'Cécile Fournier',
        nbLikes: 120,
        nbComments: 4,
        slug: 'extensions-chrome-developpeurs',
        url: 'https://example.com/extensions-chrome-developpeurs'
    },
    {
        id: 15,
        category: 'React Native',
        title: 'Introduction au développement mobile avec React Native',
        caption: 'Créez des applications mobiles avec React Native.',
        date: '2023-07-10',
        minuteToRead: 11,
        author: 'Philippe Moreau',
        nbLikes: 130,
        nbComments: 8,
        slug: 'developpement-mobile-react-native',
        url: 'https://example.com/developpement-mobile-react-native'
    },
    {
        id: 16,
        category: 'Accessibilité Web',
        title: 'Web Accessibility: A Guide',
        caption: 'Ensure your web applications are accessible to everyone.',
        date: '2023-07-05',
        minuteToRead: 10,
        author: 'Alice Martin',
        nbLikes: 115,
        nbComments: 5,
        slug: 'web-accessibility-guide',
        url: 'https://example.com/web-accessibility-guide'
    },
    {
        id: 17,
        category: 'Bootstrap',
        title: 'Introduction à Bootstrap 5',
        caption: 'Utilisez Bootstrap pour créer des sites responsives rapidement.',
        date: '2023-06-30',
        minuteToRead: 6,
        author: 'Julien Caron',
        nbLikes: 75,
        nbComments: 6,
        slug: 'introduction-a-bootstrap-5',
        url: 'https://example.com/introduction-a-bootstrap-5'
    },
    {
        id: 18,
        category: 'Développement Web',
        title: 'Les erreurs courantes en développement web',
        caption: 'Évitez ces erreurs fréquentes lors du développement de sites web.',
        date: '2023-06-25',
        minuteToRead: 8,
        author: 'Camille Dubois',
        nbLikes: 100,
        nbComments: 9,
        slug: 'erreurs-courantes-developpement-web',
        url: 'https://example.com/erreurs-courantes-developpement-web'
    }
]